apiVersion: apps/v1
kind: Deployment
metadata:
  name: farma-demoapp-dev-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farma-demo-dev-app-ui
  template:
    metadata:
      labels:
        app: farma-demo-dev-app-ui
    spec:
      containers:
      - image: ghcr.io/piseganesh123/urbanvillage:sha256-1cd0c784844ae2ca08a14bf70be9a5bcbc7a50c4f0ca637a23a9c1eaedbe381d.sig
        name: farma-demoapp-dev-ui
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: farma-demo-dev-app-ui-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
  selector:
    app: farma-demo-dev-app-ui