apiVersion: apps/v1
kind: Deployment
metadata:
  name: farma-demoapp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farma-demo-dev-app-ui
  template:
    metadata:
      labels:
        app: farma-demo-dev-app-ui
    spec:
      containers:
      - image: ghcr.io/piseganesh123/urbanvillage:sha256-5b8b426e542c8b9d62503d02ae51ec4f82575fbf91ec8c226e1de77da81ccb37.sig
        name: farma-demoapp-ui
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: farma-demo-dev-app-ui-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
  selector:
    app: farma-demo-dev-app-ui